from modules.models.config import FetcherConfig

configs = [
    FetcherConfig(base_url="https://antoshkaspb.ru", site="antoshkaspb",
                  goods_selector='.product-list > li', good_name_selector=".otw_item-name > span",
                  good_price_selectors=['.purchase meta'], window_selector='#page-content', price_is_text=False, page_format="?page="),
    FetcherConfig(base_url="https://piccolo-detki.ru", site="piccolo_detki",
                  goods_selector='#categories_view_pagination_contents > .ty-column3', good_name_selector=".product-title",
                  good_price_selectors=['.ty-price-num'], window_selector='.container-fluid', price_is_text=True, page_format="page-"),
    FetcherConfig(base_url="https://kolyaski.ru", site="kolyaski",
                  goods_selector='.product-list-block__ul > ul > li', good_name_selector=".product-list-block__h2",
                  good_price_selectors=['.new-price', '.actual-price'], window_selector='#bx_eshop_wrap', price_is_text=True, page_format="?SMART_FILTER_PATH=tipkolyaski-is-1v1-or-2v1-or-3v1-or-transformer-or-progulka-or-trost-or-dvoynya&PAGEN_2="),
    FetcherConfig(base_url="https://www.first-buggy.ru", site="first_buggy",
                  goods_selector='#products > div', good_name_selector=".main > a",
                  good_price_selectors=['.cur-price'], window_selector='#catalog', price_is_text=True, page_format="?page_4=", max_pages=11),
    FetcherConfig(base_url="https://spb.dochkisinochki.ru", site="dochkisinochki",
                  goods_selector='.esk', good_name_selector=".news_bottom .h4_span_plist > a",
                  good_price_selectors=['.yelloypriceleft .list-price'], window_selector='.allContWr', price_is_text=True, page_format="?line=&PAGEN_1=", max_pages=43),
    FetcherConfig(base_url="https://ichado.ru/", site="ichado",
                  goods_selector='.view-content > div', good_name_selector=".field-name-title a",
                  good_price_selectors=['.commerce-price-savings-formatter-price .price-amount'], window_selector='#centercol', price_is_text=True, page_format="dlya-dvoyni?page=", first_page=0),
    FetcherConfig(base_url="http://spb-kolyaska.ru/", site="spb_kolyaska",
                  goods_selector='tbody > .color2', good_name_selector=".big0",
                  good_price_selectors=['.red'], window_selector='tbody', price_is_text=True, page_format="buy.php?brand_s=&price_s=&type=&mechanism=&st=", first_page=0, step=22, max_pages=4202),
    FetcherConfig(base_url="https://www.bababum.ru", site="bababum",
                  goods_selector='.page-shop-items-list-div > div', good_name_selector=".block-items-list-content > a",
                  good_price_selectors=['.block-items-list-content .priceinlist'], window_selector='#page-shop-main-content', price_is_text=True, page_format="shop.php?cid=3&f=", first_page=1, step=20, max_pages=521),
    FetcherConfig(base_url="https://lapsi.ru", site="lapsi",
                  goods_selector='.catalog__inner .product-card', good_name_selector=".product-card__title > a",
                  good_price_selectors=['.product-card__info-line .price'], window_selector='.catalog', price_is_text=True, page_format="?PAGEN_5=", max_pages=12),
    FetcherConfig(base_url="https://msk.detkishop.com", site="detkishop",
                  goods_selector='.products-list__list > div', good_name_selector=".product-card__title",
                  good_price_selectors=['.product-card__current-price'], window_selector='.catalog', price_is_text=True, page_format="?QUERY=коляски&page=", max_pages=45),
]
